import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { JSDOM, VirtualConsole } from 'jsdom';
import { createPacksmartServer } from '../server.mjs';
import { seedWorkspaceState } from '../lib/store.mjs';
import { createSessionToken } from '../lib/security.mjs';

test('cockpit renders authenticated controls and submits real persisted workflows', async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'runvara-cockpit-'));
  const secret = 'ui-test-only-session-secret-more-than-32-characters';
  const server = createPacksmartServer({ NODE_ENV: 'test', SESSION_SECRET: secret, CREDENTIALS_KEY: 'ui-test-only-credential-key-more-than-32-characters', SAAS_STATE_FILE: path.join(directory, 'state.json'), SHOPIFY_PUBLIC_SYNC_ENABLED: 'false' });
  const state = seedWorkspaceState({}, { workspaceId: 'ui-test', email: 'ui@example.test', passwordHash: 'test-only' });
  state.products = [{ id: 'p1', title: '<img src=x onerror=alert(1)>', status: 'active', variants: [{ id: 'v1', sku: 'SKU-1', price: 10, inventory: 1, available: true }] }];
  await server.packsmart.store.save('ui-test', state);
  server.listen(0, '127.0.0.1'); await once(server, 'listening');
  const base = `http://127.0.0.1:${server.address().port}`;
  const token = createSessionToken({ userId: state.users[0].id, workspaceId: 'ui-test', email: state.users[0].email, role: 'owner', sessionVersion: 1 }, secret);
  const errors = [], calls = [], console = new VirtualConsole(); console.on('jsdomError', error => errors.push(error.message));
  const dom = new JSDOM(await fs.readFile(new URL('../../index.html', import.meta.url), 'utf8'), { url: base, runScripts: 'outside-only', virtualConsole: console, pretendToBeVisual: true });
  t.after(async () => { dom.window.close(); await new Promise(resolve => server.close(resolve)); await fs.rm(directory, { recursive: true, force: true }); });
  const { window } = dom, document = window.document;
  window.Headers = Headers; window.AbortController = AbortController; window.scrollTo = () => {}; window.HTMLElement.prototype.scrollIntoView = () => {};
  window.HTMLDialogElement.prototype.showModal = function () { this.open = true; };
  window.HTMLDialogElement.prototype.close = function () { this.open = false; this.dispatchEvent(new window.Event('close')); };
  window.fetch = async (route, options = {}) => {
    const headers = new Headers(options.headers); headers.set('Cookie', `packsmart_session=${token}`);
    const response = await fetch(base + route, { ...options, headers });
    calls.push({ route, method: options.method || 'GET', status: response.status }); return response;
  };
  const until = async condition => {
    for (let attempt = 0; attempt < 150; attempt++) { if (await condition()) return; await new Promise(resolve => setTimeout(resolve, 10)); }
    assert.fail(`UI did not reach expected state. Errors: ${errors.join('; ')}; message: ${document.querySelector('#global-error').textContent}`);
  };
  for (const file of ['presentation.js', 'control-ui.js', 'app.js']) window.eval(await fs.readFile(new URL(`../../${file}`, import.meta.url), 'utf8'));
  await until(() => !document.querySelector('#app-shell').classList.contains('hidden'));
  assert.ok(!calls.some(call => call.route === '/api/migrate-pilot'), 'a future tenant never imports the customer-zero browser cache');
  assert.equal(document.querySelector('[onerror]'), null, 'source text is escaped');
  assert.ok(document.querySelector('#attention-queue .attention-item'));
  assert.ok(!document.getElementById('attention-queue').textContent.includes('No recorded exceptions or approvals need attention.'), 'active exceptions never show an all-clear message');
  const search = document.getElementById('workspace-search-dialog'), searchInput = document.getElementById('workspace-search-input');
  const openingCalls = calls.length;
  document.getElementById('open-workspace-search').click();
  assert.equal(search.open, true);
  assert.equal(document.activeElement, searchInput);
  assert.equal(document.querySelectorAll('.search-result').length, 14);
  searchInput.value = 'billing'; searchInput.dispatchEvent(new window.Event('input'));
  assert.equal(document.querySelectorAll('.search-result').length, 1);
  assert.equal(document.querySelector('.search-result').dataset.viewLink, 'audit');
  searchInput.value = '<img src=x onerror=alert(1)>'; searchInput.dispatchEvent(new window.Event('input'));
  assert.equal(document.querySelectorAll('.search-result').length, 0);
  assert.ok(search.textContent.includes('No matching pages'));
  assert.equal(search.querySelector('[onerror]'), null);
  searchInput.value = 'approval'; searchInput.dispatchEvent(new window.Event('input'));
  searchInput.dispatchEvent(new window.KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true }));
  assert.ok(document.activeElement.classList.contains('search-result'));
  document.activeElement.click();
  assert.equal(search.open, false);
  assert.equal(searchInput.value, '');
  assert.equal(document.querySelector('.view.active').id, 'view-approvals');
  assert.equal(calls.length, openingCalls, 'workspace search is local navigation and does not fetch or mutate data');
  document.dispatchEvent(new window.KeyboardEvent('keydown', { key: 'k', ctrlKey: true, bubbles: true }));
  assert.equal(search.open, true);
  searchInput.value = 'Shopify'; searchInput.dispatchEvent(new window.Event('input'));
  searchInput.dispatchEvent(new window.KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
  assert.equal(document.querySelector('.view.active').id, 'view-channels');
  assert.equal(search.open, false);
  document.getElementById('connection-dialog').showModal();
  document.dispatchEvent(new window.KeyboardEvent('keydown', { key: 'k', ctrlKey: true, bubbles: true }));
  assert.equal(search.open, false, 'search cannot interrupt an existing connection dialog');
  document.getElementById('connection-dialog').close();
  document.querySelector('[data-period="week"]').click();
  assert.equal(document.getElementById('week-metrics').hidden, false);
  assert.equal(document.getElementById('month-metrics').hidden, true);
  assert.equal(document.querySelector('[data-period="week"]').getAttribute('aria-pressed'), 'true');
  document.querySelector('[data-period="month"]').click();
  assert.equal(document.getElementById('week-metrics').hidden, true);
  assert.equal(document.getElementById('month-metrics').hidden, false);
  assert.ok(document.getElementById('revenue-chart').textContent.includes('No channel revenue is available yet'));
  for (const button of document.querySelectorAll('#main-nav [data-view]')) { button.click(); assert.ok(document.getElementById(`view-${button.dataset.view}`).classList.contains('active')); }
  const decision = document.getElementById('decision-form');
  for (const [key, value] of Object.entries({ key: 'ui-goal', category: 'goal', title: 'A verified UI goal', content: 'Check operations daily.', source: 'DOM integration test' })) decision.elements[key].value = value;
  decision.dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true }));
  await until(() => document.getElementById('decision-list').textContent.includes('A verified UI goal'));
  document.getElementById('autopilot-toggle').click();
  await until(() => document.getElementById('autopilot-status').textContent.startsWith('ON'));
  const opportunity = document.querySelector('[data-opportunity]'); assert.ok(opportunity); opportunity.click();
  await until(() => document.querySelector('[data-modify-approval]'));
  document.querySelector('[data-modify-approval]').click();
  const edit = document.getElementById('approval-edit-form'); edit.elements.action.value = 'Revised UI proposal';
  edit.dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true }));
  await until(() => document.getElementById('approval-list').textContent.includes('Revised UI proposal'));
  document.querySelector('[data-approval][data-decision="approved"]').click();
  await until(() => calls.some(call => call.route.endsWith('/decision') && call.status === 200));
  const agent = document.querySelector('[data-agent-form="stock"]'); agent.elements.enabled.value = 'false';
  agent.dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true }));
  await until(async () => (await server.packsmart.store.get('ui-test')).agentSettings.stock.enabled === false);
  await until(() => document.getElementById('global-success').textContent === 'Agent policy saved.');
  const saved = await server.packsmart.store.get('ui-test');
  assert.equal(saved.approvals[0].status, 'approved'); assert.equal(saved.approvals[0].revision, 2);
  assert.equal(saved.approvals[0].executedExternally, false); assert.ok(saved.decisions.some(item => item.key === 'ui-goal'));
  assert.deepEqual(errors, []); assert.ok(!calls.some(call => call.status >= 400));
  await t.test('Commander console renders real delegation and preserves approval gates', async () => {
    const form = document.getElementById('commander-form'), card = form.closest('.command-card');
    const input = form.elements.command, button = form.querySelector('button');
    const result = document.getElementById('commander-result');
    // jsdom does not implement browser named properties on HTMLFormElement.
    Object.defineProperty(form, 'command', { value: input });
    const submit = async command => {
      input.value = command;
      form.dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true }));
      assert.equal(card.getAttribute('aria-busy'), 'true'); assert.equal(button.disabled, true);
      await until(() => card.getAttribute('aria-busy') === 'false');
      assert.equal(button.disabled, false);
    };
    await submit('Check pricing');
    let recorded = await server.packsmart.store.get('ui-test'), run = recorded.agentRuns[0];
    assert.equal(document.getElementById('commander-error').textContent, '');
    assert.equal(result.classList.contains('hidden'), false);
    assert.equal(result.querySelector('.brief-result-summary').textContent, run.summary);
    assert.deepEqual([...result.querySelectorAll('.delegation-chip')].map(chip => chip.textContent), ['Pricing & Margin']);
    assert.equal(document.getElementById('commander-team-size').textContent, '14 specialists');
    assert.equal(document.querySelectorAll('#agent-grid .agent-mark svg').length, 15);
    assert.equal(document.querySelectorAll('[data-agent-form]').length, 15);
    assert.equal(recorded.products.length, 1);
    assert.equal(run.executedExternally, false);
    assert.equal(result.querySelector('[onerror]'), null);
    await submit('Change prices for all products');
    recorded = await server.packsmart.store.get('ui-test'); run = recorded.agentRuns[0];
    assert.equal(result.querySelector('.brief-result-heading .tag').textContent, 'REQUIRES APPROVAL');
    assert.equal(run.workStatus, 'REQUIRES APPROVAL');
    assert.equal(recorded.approvals.find(item => item.id === run.approvalId).status, 'pending');
    assert.equal(run.executedExternally, false);
    assert.equal(recorded.products[0].variants[0].price, 10);
    assert.equal(result.querySelector('.brief-result-summary').textContent, run.summary);
    recorded.agentSettings.commander.enabled = false;
    await server.packsmart.store.save('ui-test', recorded);
    const runCount = recorded.agentRuns.length;
    await submit('Check pricing');
    assert.match(document.getElementById('commander-error').textContent, /disabled/i);
    assert.equal(input.value, 'Check pricing', 'a failed command remains available to retry');
    assert.equal((await server.packsmart.store.get('ui-test')).agentRuns.length, runCount);
    assert.deepEqual(errors, []);
  });
  const bootstrap = await (await window.fetch('/api/bootstrap')).json();
  for (const scenario of [
    { name: 'chart keeps positive, negative, zero and unavailable revenue distinct', values: [250, -50, 0, null] },
    { name: 'chart treats no channels as an empty state', values: [] },
    { name: 'chart does not turn an unknown value into zero', values: [null, undefined] }
  ]) await t.test(scenario.name, async () => {
    const chartErrors = [], virtualConsole = new VirtualConsole(); virtualConsole.on('jsdomError', error => chartErrors.push(error.message));
    const chartDom = new JSDOM(await fs.readFile(new URL('../../index.html', import.meta.url), 'utf8'), { url: base, runScripts: 'outside-only', virtualConsole });
    try {
      const w = chartDom.window;
      w.Headers = Headers; w.AbortController = AbortController; w.scrollTo = () => {};
      w.RunvaraControl = { init() {}, render() {}, evidence() { return ''; }, history() { return ''; } };
      const data = { ...bootstrap, integrations: scenario.values.map((revenue, index) => ({ id: 'channel-' + index, name: index ? 'Channel ' + index : '<img src=x onerror=alert(1)>', kind: 'commerce', status: 'connected', metrics30d: { revenue } })) };
      w.fetch = async route => new Response(JSON.stringify(route === '/api/auth/session' ? { user: bootstrap.user, workspace: bootstrap.workspace, csrf: bootstrap.csrf } : data), { status: 200 });
      w.eval(await fs.readFile(new URL('../../presentation.js', import.meta.url), 'utf8'));
      w.eval(await fs.readFile(new URL('../../app.js', import.meta.url), 'utf8'));
      for (let i = 0; i < 100 && w.document.getElementById('app-shell').classList.contains('hidden'); i++) await new Promise(resolve => setTimeout(resolve, 5));
      assert.equal(w.document.getElementById('app-shell').classList.contains('hidden'), false, w.document.getElementById('startup-error').textContent + '; ' + chartErrors.join('; '));
      const chart = w.document.getElementById('revenue-chart');
      assert.equal(chart.querySelector('[onerror]'), null);
      if (scenario.values.length === 4) {
        const rows = chart.querySelectorAll('.revenue-row');
        assert.equal(rows.length, 4);
        assert.equal(rows[0].querySelector('strong').textContent, '£250.00');
        assert.equal(rows[1].querySelector('strong').textContent, '-£50.00');
        assert.equal(rows[2].querySelector('strong').textContent, '£0.00');
        assert.equal(rows[3].querySelector('strong').textContent, '—');
        assert.equal(rows[0].querySelector('.revenue-bar').getAttribute('width'), '833.33');
        assert.equal(rows[1].querySelector('.revenue-bar').getAttribute('x'), '0.00');
        assert.equal(rows[1].querySelector('.revenue-bar').getAttribute('width'), '166.67');
        assert.equal(rows[2].querySelector('.revenue-bar').getAttribute('width'), '0.00');
        assert.equal(rows[3].querySelector('svg'), null);
      } else assert.ok(chart.textContent.includes('No channel revenue is available yet'));
      assert.deepEqual(chartErrors, []);
    } finally { chartDom.window.close(); }
  });
  document.getElementById('open-workspace-search').click();
  document.getElementById('logout').click();
  await until(() => document.getElementById('app-shell').classList.contains('hidden'));
  await until(() => document.getElementById('signup-form').elements.invitation.required);
  assert.equal(search.open, false, 'sign-out closes the navigation overlay');
  assert.equal(document.getElementById('workspace-search-results').childElementCount, 0);
  assert.equal(document.getElementById('commander-result').childElementCount, 0, 'sign-out clears the previous workspace brief');
  assert.equal(document.getElementById('commander-result').classList.contains('hidden'), true);
  document.dispatchEvent(new window.KeyboardEvent('keydown', { key: 'k', ctrlKey: true, bubbles: true }));
  assert.equal(search.open, false, 'a signed-out user cannot open workspace navigation');
});
